// Generated by CoffeeScript 1.6.3
(function() {
  var make_slot;

  make_slot = function() {
    var latest_unique, slot;
    latest_unique = {};
    slot = function(callback) {
      var callback_unique;
      callback_unique = {};
      latest_unique = callback_unique;
      return function() {
        if (callback_unique === latest_unique) {
          return callback.apply(this, arguments);
        }
      };
    };
    slot.clear = function() {
      return slot(function() {});
    };
    return slot;
  };

  module.exports = make_slot;

}).call(this);
